### ISSUE TITLE
[V2] Analyzing the dependency graph

### ISSUE THREAD

**Issue by juandopazo** [yahoo/mendel#100]
Hey @irae @stephanwlee! What's a good way, now that there are no manifests, to analyze the dependency graph?

**Comment by muralikr** [comment]
@juandopazo Manifests are generated when we run `mendel` without watch argument.

**Comment by juandopazo** [comment]
Oh interesting...

**Comment by juandopazo** [comment]
I guess I'll have to write my own `disc` tho

**Comment by irae** [comment]
Yeah! I've been thinking of writing Disc for Mendel for a long while, since V2 I guess.

I want to get diff - view of manifests too, maybe even disc with diff! lol @juandopazo the possibilities are endless. To be honest, this relates a lot to what I said on the other issue today, bringing back post process manifest is a neat way to plug disc-like statistics.

You know, I just had another idea, what about a version of disc with variations and multi layer. Really, the only thing that changes is an input array, it can use mendel-trees internally to get exactly the same as a production package.
