### ISSUE TITLE
Mendel and Webpack

### ISSUE THREAD

**Issue by AshleyAitken** [yahoo/mendel#139]
Hi,

Thank you for open sourcing Mendel.

I saw in your GitHub docs that you used Browserify for Mendel's implementation because it was more extensible and Webpack wasn't popular (or didn't exist) at the time.

We have a lot of commitment to Webpack and wonder whether you are considering a possible future implementation with Webpack? 

Thanks,
Ashley.

**Comment by irae** [comment]
The Mendel strategy and mental model is easy to implement in Webpack, and we looked at it at different point in time.

> TL;DR: Webpack is awesome, but Mendel introduces a number of innovations and has plans for the future that make it not worth to adopt Webpack internally.

Mendel started as a proprietary implementation inside Search, it is still in production for Search Mobile iOS as far as I can tell, it uses Browserify on development server and it uses broccoli and browserify to generate production bundles. At the time, Q3 2014 we did Webpack research and couldn't get enough performance from it and could not integrate well with karma for unit testing with buckets.

When I joined Mail and took over similar responsibilities, we had a second look at webpack in Q4 2016. We again chose Browserify over Webpack. Modularity is important when you have custom code and open source mixed together, but Webpack is more like a huge repo that can do so much features. This is good and bad at the same time, because we felt we would need to fork Webpack instead of using internals of Browserify (they publish so much core packages it makes it easier).

But really, Mendel v3 was panned and executed because we figured out we need a new strategy for compiling/transpiring assets. It is a different paradigm entirely. All tools out there configure transforms per bundle. This is the culprit of all the issues, be it performance, be it being hard to configure and imprecise. This makes it very hard to do multi-bundles, with many variations, and/or A/B testing buckets and all the scale issues I explained on the podcast.

I need to create some graphics of whit this is so. I compared the internals and pipeline architecture for browserify, webpack, rollup and came up with the Mendel internal architecture which is a huge improvement in comparison to the mentioned builders.

To go back to your question, it is feasible to re-implement Mendel with Webpack, but it would be a step back. If you would like to get all benefits from Mendel that are not present in Webpack, you would need instead to rewrite Webpack core adopting Mendel's internal architecture. In fact, Mendel internals can be easily re-used. But it is a huge lot of work to do this and undergo compatibility changes. So you see, I really think Mendel needs to exist in separation. I wish I could be full time working on Mendel again, there is so much that can be done here, but right now I am very engaged at the startup I am working on, so it will take a while for me to come back and finish what I started.

Here are some features I have planned for Mendel that are not even close to complete:

  * Rollup style context-hoisting: This would replace browser-pack module system by something like Rollup and Closure compiler does, that you remove the require statement by accessing functions/objects directly while bookkeeping and avoiding naming collisions.
  * Rollup/Webpack style tree shaking: Both the above and tree shaking can't be computationally efficient (like creating 6k+ production bundles) without rewriting the algorithm to be variation aware, I expect (just a guess) to loose something like 2 to 5% of dead code removal to allow variations to exist, but it should be a fair tradeoff.
  * Differential loading: When you deploy a bundle of 100k or so, and on next deployment just 2k changed, we can deploy just the changes if we use a combination of tracking past Mendel-manifests and encrypted cookies (to allow for higher security) to deploy just the 2k when we know the user has the remaining payload cached. We don't even need to rely on ServiceWorkers for that. Coming for a 3rd world country myself, I would prefer ServiceWorkers to be an option and not a requirement for such optimization.
  * HTTP2/SPDY and Service Workers improvements: No, sending each module separate is not the final solution, there is a number of strategies that are even faster than relying only on HTTP2. The approach could be smarter and because Mendel is architected around a manifest in production, we can do smarter decisions than any other automatic system out there.

Dont' take me wrong, I love Webpack and have used it in other projects. But Mendel is aiming way higher. Builds that would take maybe 5 minutes in Webpack are taking 15 seconds with Mendel. Not to mention blazing fast sub-second development server to boot and under 50ms for serving a single bundle in development before caching.

Thanks again for writing, and let me know if you have further questions.
Irae
