### ISSUE TITLE
Fix Configuration for Bundle/Outlet

### ISSUE THREAD

**Issue by stephanwlee** [yahoo/mendel#73]
In some bundle, you want to bundle everything of certain *type* without walking dependency graph (CSS?) However, since a bundle contains single type (unless exception comes up; let's see what happens then), type should/does declare what kind of outlet is appropriate.  It seems like bundle should contain type information or entry "files".

Also, `entries` in bundles have a path. Should it be relative path from .mendelrc or should it be relative path from base variation directory?

**Comment by irae** [comment]
As for the second question: All entries should be relative to variation. Here are some reasons I moved from "relative to basedir" to "realative to variation":

  * shorter to type
  * not prone to ambiguity, such as `src/variations/foo/bar.js` being on a list of entries, should it be included if I request the "base" variation?
  * when you try to variate an entry (i.e. "entries: main.js" when both `src/base/main.js` and `variation/foo/main.js` exist) it can work from scratch, supported by mendel correctly.

As for the `types` question, I think this is more of a design question, it relates a lot to the "parser-to-type" feature. You might have a problem if you don't traverse the graph because of some output being of the type you are looking for. 

I think you can achieve what you explained with a generator. Similar to `mendel-generator-node-modules`. For instance, without declaring the "input types" or "output type" to "mendel" itself, those options could be generator options instead. Besides: what are the real benefits of not running the whole graph?

**Comment by irae** [comment]
I am closing this because we do support globs now, and I think this answers both questions. Please comment if otherwise.
