### ISSUE TITLE
Custom resolvers

### ISSUE THREAD

**Issue by juandopazo** [yahoo/mendel#94]
Hey @irae @stephanwlee! What do you think about the possibility of supporting custom resolvers? In particular, for directories. For example, let's say I want to support `require('foo/bar')` and have `foo` resolve to `'./foo1/foo2/foo3' before resolving variations. Would this make sense? How hard do you think it would be to implement?

**Comment by irae** [comment]
The same "feature" is already supported by the use of `package.json`. If you are going to make this real quick just to solve a variation you can use symlinks too.

I think custom resolvers might break the mental model. CommonJS and npm module resoluction through `package.json` is already pretty hard, but it is a standard and works well for NodeJS. Introducing custom resolvers will make every mendel codebase feel very different, I am not sure it is worth.

When you commit a new `package.json` on the other hand, you are self-documenting the exception in a declarative way.

**Comment by juandopazo** [comment]
Well, what I'm considering is adding more options to `package.json`.

**Comment by stephanwlee** [comment]
Current resolver supports `runtime` which allows you to introduce any type of option in `package.json`. Currently, it is set somewhere to look only at `['browser', 'main']`.

**Comment by juandopazo** [comment]
😮 That's perfect!

**Comment by irae** [comment]
Can you elaborate or send examples of why this is needed?

Resolving `package.json` stuff creates a whole mess. We do have checks to throw during build and enforce that you use `package.json` in the same way across variations.

For instance:
```
src/base/foo/index.js
src/variations/bar/foo/package.json → {main: './some/other.js'}
``
This will throw during build time, because it breaks our compilation and serialization in so many ways it makes distributed build impossible. For instance, in order to generate manifests correctly and apply variations with multi-layer, we need to make sure internally that the both files mentioned above are actually the same "file" but changes content based on variation.

@juandopazo remember this is building a number of different graphs that need to be compatible and merged. If you have many different `package.json` and you can create a lot of inconsistencies. So you are really stepping into something pretty hard to make "generic".

**Comment by irae** [comment]
Well, if you want to introduce it, it's all good to me. But I am still left not understanding what you need to achieve that `package.json` does not provide yet.

**Comment by stephanwlee** [comment]
I feel the same as @irae. If you must do it, make sure every part of Mendel is capable of using the runtime information. I believe some parts are not accounting it properly.

**Comment by juandopazo** [comment]
I'm evaluating whether I need different bundles with different versions of a specific file, while retaining a similar dependency graph. Let's say I have A -> B -> C. I might want a new bundle with a different C but same A and B.

I was thinking of using `package.json` as `{ main: '', browser: '', myotherbundle: ''}`.

**Comment by irae** [comment]
Maybe you don't fully understand mendel's mental model.

There is two ways of doing this:

1. Duplicate C on a variation.
2. Duplicate file that requires C in a variation and require something else or omit the require.

The duplication is a way to enforce that variations should be either short lived or code needs to be refactored to accommodate a permanent or long term variation. If you make it super easy to "remap" files, those will be forever forgotten on "base" (or whatever you call your main variation) and you will not have easy disposability of variation. You would be making it easy to create a variation as opposed to make easy to dispose of it.

You can also have some variations have "C" to be a null operation.

For instance, I have a project using mendel that we have a custom debug visualization for developers only. We created a variation "devel" which no user is assigned by accident, just available to developers though query string. This has a `<Debug />` component implmentation and on baseline `debug.jsx` is just a function that returns null. This allows my code to be simple and overhead is kept at a minimum for users. If you don't want this in production, just wrap the require in NODE_ENV use and you are good to go.

**Comment by juandopazo** [comment]
Yeah this wouldn't be a short lived thing, that's why I'm not considering variations. In fact, I could need variations of this new "runtime" version.

**Comment by juandopazo** [comment]
The other reason I'm not keen on using variations for this is the "out of sight, out of mind" effect of having them in an "experiments" folder. I think that works very well for experiments, but for something permanent I'd rather have the files in the same place so it's obvious that if you mess with one you should consider the other one.

**Comment by irae** [comment]
Well, maybe mendel is not for you? 😆 

I've seen similar examples of what you are saying. You want an easy way to follow variations on a folder that it is not called `variations` or `experiments`. BTW, mendelv2 supports multiple variational folders, so potentially you can have folders such as `partners/foo` that are intended for long-term and `experiments` for short term.

You have access to all of it. Go to some products that use buckets on da daily bases, such as any of the Search FEs you have there at Yahoo. You will find "plain in your face" experiments and variations from ages ago that were never cleaned up. Then you go to the particular one you know I maintained and we extracted Mendel from, you will find maybe 4 variations, all are likely disabled and there is zero tech debt. You just delete the folder. The whole reason @jlecomte sponsored Mendel is because "quick conditionals" living on the same place makes up for a huge tech debt over time.

When you say "custom resolvers" I imagine something way deeper than quick experiments, I think something like supporting github URLs to fetch master, or supporting npm packages over cached HTTP or even wrapping elements in HOCs automatically based on something that is not a variation. I think there is potential there, but not for the particular reason you pointed too.

For instance, a smart version of `mendel-resolver-react-intl` might use custom resolvers to get the strings bundled in the same `app.js` bundle, as opposed for the extra HTTP request people using `react-intl` currently solves. But I think if in any way you can support what you need by use of variations, I believe you should do so, instead of implementing custom resolvers.

**Comment by juandopazo** [comment]
Supporting multiple "runtimes" could do the trick for me and it looks like it should be a change of only a few lines of code. Do you think it's worth it?

**Comment by irae** [comment]
IDK, I don't fully understand the benefits you are seeing.
I think @stephanwlee hinted of it being larger than you make it sound. For instance, MendelTrees (inside `mendel-core`) is a second place to solve this. Also the development middleware. I don't think it will be straightforward to find all places runtime is hardcoded, not to mention integration with plugins.

**Comment by irae** [comment]
I am not at all against it, I just ask you to post a more reasonable example use case in one of the Markdown files alongside a PR so we have a documented example.

**Comment by juandopazo** [comment]
Fair enough. It might still be that I need changes in my whole dependency tree so I might not really need anything new. And I'm going to look into custom variation folders.

Thanks!

**Comment by juandopazo** [comment]
Looks like we're either rewriting a lot of stuff or going with variations 👍
